# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/getz/project_11/project_11.srcs/sources_1/bd/memristor/ip/memristor_ADC_1_0/memristor_ADC_1_0.xci
# IP: The module: 'memristor_ADC_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/getz/project_11/project_11.gen/sources_1/bd/memristor/ip/memristor_ADC_1_0/memristor_ADC_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'memristor_ADC_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/getz/project_11/project_11.gen/sources_1/bd/memristor/ip/memristor_ADC_1_0/memristor_ADC_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'memristor_ADC_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/getz/project_11/project_11.gen/sources_1/bd/memristor/ip/memristor_ADC_1_0/memristor_ADC_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'memristor_ADC_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/getz/project_11/project_11.srcs/sources_1/bd/memristor/ip/memristor_ADC_1_0/memristor_ADC_1_0.xci
# IP: The module: 'memristor_ADC_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/getz/project_11/project_11.gen/sources_1/bd/memristor/ip/memristor_ADC_1_0/memristor_ADC_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'memristor_ADC_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/getz/project_11/project_11.gen/sources_1/bd/memristor/ip/memristor_ADC_1_0/memristor_ADC_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'memristor_ADC_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/getz/project_11/project_11.gen/sources_1/bd/memristor/ip/memristor_ADC_1_0/memristor_ADC_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'memristor_ADC_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
