# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/ZCU702_Projects/ZCU702_memristor/design/project_11.srcs/sources_1/bd/memristor/ip/memristor_PGA_SPI_0/memristor_PGA_SPI_0.xci
# IP: The module: 'memristor_PGA_SPI_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ZCU702_Projects/ZCU702_memristor/design/project_11.gen/sources_1/bd/memristor/ip/memristor_PGA_SPI_0/memristor_PGA_SPI_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'memristor_PGA_SPI_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/ZCU702_Projects/ZCU702_memristor/design/project_11.gen/sources_1/bd/memristor/ip/memristor_PGA_SPI_0/memristor_PGA_SPI_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'memristor_PGA_SPI_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/ZCU702_Projects/ZCU702_memristor/design/project_11.gen/sources_1/bd/memristor/ip/memristor_PGA_SPI_0/memristor_PGA_SPI_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'memristor_PGA_SPI_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/ZCU702_Projects/ZCU702_memristor/design/project_11.gen/sources_1/bd/memristor/ip/memristor_PGA_SPI_0/memristor_PGA_SPI_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'memristor_PGA_SPI_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/ZCU702_Projects/ZCU702_memristor/design/project_11.srcs/sources_1/bd/memristor/ip/memristor_PGA_SPI_0/memristor_PGA_SPI_0.xci
# IP: The module: 'memristor_PGA_SPI_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ZCU702_Projects/ZCU702_memristor/design/project_11.gen/sources_1/bd/memristor/ip/memristor_PGA_SPI_0/memristor_PGA_SPI_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'memristor_PGA_SPI_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/ZCU702_Projects/ZCU702_memristor/design/project_11.gen/sources_1/bd/memristor/ip/memristor_PGA_SPI_0/memristor_PGA_SPI_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'memristor_PGA_SPI_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/ZCU702_Projects/ZCU702_memristor/design/project_11.gen/sources_1/bd/memristor/ip/memristor_PGA_SPI_0/memristor_PGA_SPI_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'memristor_PGA_SPI_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/ZCU702_Projects/ZCU702_memristor/design/project_11.gen/sources_1/bd/memristor/ip/memristor_PGA_SPI_0/memristor_PGA_SPI_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'memristor_PGA_SPI_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
