# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/zc702.xdc

# Block Designs: bd/memristor/memristor.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==memristor || ORIG_REF_NAME==memristor} -quiet] -quiet

# IP: bd/memristor/ip/memristor_ADC_1_0/memristor_ADC_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==memristor_ADC_1_0 || ORIG_REF_NAME==memristor_ADC_1_0} -quiet] -quiet

# IP: bd/memristor/ip/memristor_ADC_2_0/memristor_ADC_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==memristor_ADC_2_0 || ORIG_REF_NAME==memristor_ADC_2_0} -quiet] -quiet

# IP: bd/memristor/ip/memristor_ADC_3_0/memristor_ADC_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==memristor_ADC_3_0 || ORIG_REF_NAME==memristor_ADC_3_0} -quiet] -quiet

# IP: bd/memristor/ip/memristor_ADC_4_0/memristor_ADC_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==memristor_ADC_4_0 || ORIG_REF_NAME==memristor_ADC_4_0} -quiet] -quiet

# IP: bd/memristor/ip/memristor_CTRL_WEST_0/memristor_CTRL_WEST_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==memristor_CTRL_WEST_0 || ORIG_REF_NAME==memristor_CTRL_WEST_0} -quiet] -quiet

# IP: bd/memristor/ip/memristor_DA4_GPIO_0/memristor_DA4_GPIO_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==memristor_DA4_GPIO_0 || ORIG_REF_NAME==memristor_DA4_GPIO_0} -quiet] -quiet

# IP: bd/memristor/ip/memristor_DA4_SPI_0/memristor_DA4_SPI_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==memristor_DA4_SPI_0 || ORIG_REF_NAME==memristor_DA4_SPI_0} -quiet] -quiet

# IP: bd/memristor/ip/memristor_PGA_GPIO_0/memristor_PGA_GPIO_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==memristor_PGA_GPIO_0 || ORIG_REF_NAME==memristor_PGA_GPIO_0} -quiet] -quiet

# IP: bd/memristor/ip/memristor_PGA_SPI_0/memristor_PGA_SPI_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==memristor_PGA_SPI_0 || ORIG_REF_NAME==memristor_PGA_SPI_0} -quiet] -quiet

# IP: bd/memristor/ip/memristor_oddr_0_0/memristor_oddr_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==memristor_oddr_0_0 || ORIG_REF_NAME==memristor_oddr_0_0} -quiet] -quiet

# IP: bd/memristor/ip/memristor_processing_system7_0_0/memristor_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==memristor_processing_system7_0_0 || ORIG_REF_NAME==memristor_processing_system7_0_0} -quiet] -quiet

# IP: bd/memristor/ip/memristor_xbar_0/memristor_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==memristor_xbar_0 || ORIG_REF_NAME==memristor_xbar_0} -quiet] -quiet

# IP: bd/memristor/ip/memristor_ps7_0_axi_periph_0/memristor_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==memristor_ps7_0_axi_periph_0 || ORIG_REF_NAME==memristor_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/memristor/ip/memristor_rst_ps7_0_100M_0/memristor_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==memristor_rst_ps7_0_100M_0 || ORIG_REF_NAME==memristor_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/memristor/ip/memristor_auto_pc_0/memristor_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==memristor_auto_pc_0 || ORIG_REF_NAME==memristor_auto_pc_0} -quiet] -quiet

# XDC: c:/ZCU702_Projects/ZCU702_memristor/design/project_11.gen/sources_1/bd/memristor/memristor_ooc.xdc
