# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/getz/dev/ZCU702_memristor/design/project_11.srcs/sources_1/bd/memristor/ip/memristor_timer_0/memristor_timer_0.xci
# IP: The module: 'memristor_timer_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/getz/dev/ZCU702_memristor/design/project_11.gen/sources_1/bd/memristor/ip/memristor_timer_0/memristor_timer_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'memristor_timer_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/getz/dev/ZCU702_memristor/design/project_11.gen/sources_1/bd/memristor/ip/memristor_timer_0/memristor_timer_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'memristor_timer_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/getz/dev/ZCU702_memristor/design/project_11.srcs/sources_1/bd/memristor/ip/memristor_timer_0/memristor_timer_0.xci
# IP: The module: 'memristor_timer_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/getz/dev/ZCU702_memristor/design/project_11.gen/sources_1/bd/memristor/ip/memristor_timer_0/memristor_timer_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'memristor_timer_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/getz/dev/ZCU702_memristor/design/project_11.gen/sources_1/bd/memristor/ip/memristor_timer_0/memristor_timer_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'memristor_timer_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
